[logger]
level = "error"
messageFormat = "%(asctime)s %(message)s"

[runner]
fastReruns = true

[server]
headless = true

[theme]
primaryColor = "#0068C9"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[client]
toolbarMode = "minimal"
showErrorDetails = false

[ui]
hideTopBar = false
hideSidebarNav = false
